language: objective-c
osx_image: xcode7.3
xcode_sdk:
  - iphonesimulator8.1
  - iphonesimulator8.2
  - iphonesimulator8.3
  - iphonesimulator8.4
  - iphonesimulator9.0
  - iphonesimulator9.1
  - iphonesimulator9.2
  - iphonesimulator9.3
before_install: sudo motion update
script: bundle exec rake spec
deploy:
  provider: rubygems
  api_key:
    secure: BA4jK37Z5iul3szro9p1YP7MScgbQ9ITEiJD01FBjQGBPXWteomYD9NF0dV0aDk+RHAQEogoX5Ubkmt8MKlo/72nosMGR56n+IbNkmcdpsykg8Bb62e/ZuYpnu7OvK3M9cgeq+HskHsRPQWoDoM5GnkNHMfx7ecp1a1bJ8eP614=
  gem: motion-support
  on:
    tags: true
    repo: rubymotion/motion-support
