language: objective-c

osx_image:
  - xcode7.1
  - xcode7.0
  - xcode6.4

env:
  global:
    - COCOAPODS_NO_REPO_UPDATE_OUTPUT=true

before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update
  - pod setup > /dev/null

install:
  - bundle install
  - bundle exec rake pod:install > /dev/null

cache:
  directories:
    - vendor/bundle
    - vendor/Pods
    - ~/Library/Caches/CocoaPods/
    - ~/.cocoapods/repos/master/

script: bundle exec rake spec
deploy:
  provider: rubygems
  api_key:
    secure: BA4jK37Z5iul3szro9p1YP7MScgbQ9ITEiJD01FBjQGBPXWteomYD9NF0dV0aDk+RHAQEogoX5Ubkmt8MKlo/72nosMGR56n+IbNkmcdpsykg8Bb62e/ZuYpnu7OvK3M9cgeq+HskHsRPQWoDoM5GnkNHMfx7ecp1a1bJ8eP614=
  gem: motion-support
  on:
    tags: true
    repo: rubymotion/motion-support
